# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Build Azure Machine Learning Service!
  displayName: 'Build the Azure Machine Learning service'

- task: Docker@2
  inputs:
    containerRegistry: 'sesam-rd-docker-registry'
    repository: 'sesamrd/aws-elastic-search-source'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest